# Generated by Django 4.0 on 2021-12-28 17:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('blog', '0002_alter_post_id_comment'),
    ]

    operations = {
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem',
                                                  to='taggit.Tag',
                                                  verbose_name='Tags'),
        ),
    }
